### ISSUE TITLE
[v0] holders'balance not equal query from contract'balance method

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#377] opened 2022-04-14 06:37 UTC
token url:https://gwscan.com/token/49056?tab=holders&id=49056&page=1
token contract url:https://gwscan.com/account/0x2ab78093f76c95f0f8da2596584b5d533867702b?tab=contract
![image](https://user-images.githubusercontent.com/32102187/163327817-c319b012-19ef-4d1d-bdc8-88737b43443e.png)
![image](https://user-images.githubusercontent.com/32102187/163327920-81049498-ac94-4910-af8a-9a5c8d5ff2e7.png)

**Comment by zmcNotafraid** [comment] 2022-05-05 06:59
This bug is caused by the multiple block sync. When we sync the two block together, prev block A receive the token  and next block A send the token to B.So both block have same account A and same token 's transfer. Before import data we need to unique the account and token, but we keep the first data and lost the last data, so we only import the record that A receive the token.
To fix this bug, we need to keep the last transfer data.

**Comment by zmcNotafraid** [comment] 2022-05-06 04:25
All data have fixed now

**Comment by Keith-CY** [comment] 2022-05-26 08:47
![image](https://user-images.githubusercontent.com/7271329/170453266-a0602c92-d28d-4b02-b316-5c0636d7fc84.png)
There're still accounts having incorrect balances

**Closed** 2022-08-03 03:29 UTC
Labels: bug
