### ISSUE TITLE
The off-edge margins need to be consistent across all pages.

### ISSUE THREAD

**Issue by Kirl70** [Magickbase/godwoken_explorer#878] opened 2022-08-22 02:42 UTC
Currently there are two different spacings, they appear on different pages, please check them and modify them to the same spacing.

<img width="1642" alt="image" src="https://user-images.githubusercontent.com/106060898/185827816-9887e134-a96c-4ed9-8667-7a6d339bdf2a.png">

<img width="1750" alt="image" src="https://user-images.githubusercontent.com/106060898/185827711-aee4b165-092c-4179-9c16-d76beb353d29.png">

<img width="1787" alt="image" src="https://user-images.githubusercontent.com/106060898/185827755-674a6a89-d678-42d4-9728-5a2ac8a54e13.png">

<img width="1718" alt="image" src="https://user-images.githubusercontent.com/106060898/185827913-e867c160-ccfc-4cc7-bf0f-df078357dcce.png">

**Comment by qiweiii** [comment] 2022-08-22 08:50
fixed by: https://github.com/Magickbase/godwoken-explorer-ui/pull/480

**Comment by Kirl70** [comment] 2022-08-22 09:15
Regarding the issue of different page offsets, besides me, @Keith-CY also had this issue
Please check this question again @qiweiii

**Comment by qiweiii** [comment] 2022-08-22 11:27
Fixed, it's caused by scroll bar

**Comment by Kirl70** [comment] 2022-08-23 01:12
Verified

**Closed** 2022-08-23 01:12 UTC
Labels: bug
